import Navbar from './navbar.jsx';
import './globals.css';
// import { SpeedInsights } from '@vercel/speed-insights/next';
// import { Analytics } from '@vercel/analytics/react';

export const metadata = {
	title: 'Final Degree Project',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				<div className="container">{children}</div>
			</body>
		</html>
	);
}
